version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8080:8080"
